export const ADD_INGREDIENCE = 'ADD_INGREDIENCE';
export const REMOVE_INGREDIENCE = 'REMOVE_INGREDIENCE';
export const GET_ALL_INGREDIENCE = 'GET_ALL_INGREDIENCE';
export const GET_ALL_ERROR_INGREDIENCE = 'GET_ALL_ERROR_INGREDIENCE';
export const SHOW_SPINNER = 'SHOW_SPINNER';

export const LIGHT_ON = 'LIGHT_ON';
export const LIGHT_OFF = 'LIGHT_OFF';
export const LIGHT_TOGGLE = 'LIGHT_TOGGLE';